### ISSUE TITLE
Make the API more Object Oriented (?)

### ISSUE THREAD

**Issue by theXappy** [diogotr7/Vulcan.NET#1]
Hey, cool project @diogotr7 
I got it to work with my Vulcan in no time.

I want to suggest changing the way the VulcanKeyboard class is handled:
 Instead of a static class, which keeps the entire state in static members, maybe allow creation of instance(s) that represent the connected keyboard?
It feels more natural to me in a language like C#

I forked your repo and implemented it in https://github.com/Wootness/Vulcan.NET
I can make a pull request if you're interested or you can just clone me repo and copy the code

Cheers

**Comment by diogotr7** [comment]
I could see having a way of finding every compatible keyboard connected to the system, which you could then use in the constructor of the actual keyboard control class? Would have the benefit of supporting multiple keyboards at the same time.

Feel free to pull request it :smile:

**Comment by theXappy** [comment]
Created : #2 
Multiple keyboards connected to the same PC sounds funny, I don't think it's worth writing code to detected multiple keyboards when most people only use 1 :)

One of the reasons I like the VulcanKeyboard class to be non-static even if we aren't expecting multiple keyboards is that it can be IDisposable so you can use it in 'using' statements (Like I used in the TestApp)

**Comment by diogotr7** [comment]
The reason I wrote this was because of this here : https://github.com/antonpup/Aurora

And using a static class just made it slightly easier. I will look at the pull when I have time :)
